config/routes.rb
Rails.application.routes.draw do
	resources :words
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/definition.rb
class Definition < ApplicationRecord
	belongs_to :word, inverse_of: :definitions
end

app/models/word.rb
class Word < ApplicationRecord
	has_many :definitions, dependent: :destroy, inverse_of: :word
	accepts_nested_attributes_for :definitions, reject_if: proc { |attributes| attributes[:body].blank?}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
before_action :set_word, only: [:show, :edit, :update, :destroy]

  def index
  	@words = Word.all
  end

  def new
  	@word = Word.new
  	@word.definitions.build
  end

  def create
  	@word = Word.new(secure_params)
  	if @word.save
  		flash[:notice] = "Successfully created new word"
  		redirect_to words_path
  	else
  		flash[:notice] = "Unable to create new word"
  		render :new
  	end
  end

  def show
  end

  def edit
  end

  def update
  	if @word.update_attributes(secure_params)
  		redirect_to @word, notice: 'Successfully updated word'
  	else
  		render :edit
  	end
  end

  def destroy
  	@word.destroy
  	redirect_to words_path
  end

  private

  def secure_params
  	params.require(:word).permit(:title, definitions_attributes: [:id, :body])
  end

  def set_word
  	@word = Word.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wordkeep</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/words/edit.html.erb
<h2>Edit Word:</h2>
<%= form_for @word do |w| %>
	<%= w.label :title %>
	<%= w.text_field :title %>
	<%= w.fields_for :definitions do |d| %>
		<%= d.label :body %>
		<%= d.text_field :body %>
	<% end %>
	<%= w.submit "Update" %>
<% end %>

<li><%= link_to "View all Words", words_path %></li>
<li><%= link_to "View this Word", word_path(@word) %></li>

app/views/words/index.html.erb
<h1>View all Words:</h1>

<% for word in @words %>
	<h4><%= word.title %></h4>
	<% for definition in word.definitions %>
		<p><%= definition.body %></p>
	<% end %>
	<li><%= link_to "View", word_path(word.id) %></li>
	<li><%= link_to "Update", word_path(word.id) %></li>
	<li><%= link_to "Delete", word_path(word.id), method: :delete, data: {confirm: 'Are you sure?'}%></li>
<% end %>

<li><%= link_to "Create new word", new_word_path %></li>

app/views/words/new.html.erb
<h2>Create a new Word</h2>
<%= form_for @word do |w| %>
	<%= w.label :title %>
	<%= w.text_field :title %>
	<%= w.fields_for :definitions do |d| %>
		<%= d.label :body %>
		<%= d.text_area :body, size: "30x10" %>
	<% end %>
	<%= w.submit 'Create Word' %>
<% end %>

<li><%= link_to "View all Words", words_path %></li>

app/views/words/show.html.erb
<h4><%= @word.title %></h4>
<% for definition in @word.definitions %>
	<p><%= definition.body %></p>
<% end %>

<li><%= link_to "View all Words", words_path %></li>
<li><%= link_to "Edit this Word", edit_word_path(@word) %></li>